const fs = require("fs")
const {convertToCSV} = require("convert-to-csv")




const data = [
    {
        "name": "SHANNON M BLACK",
        "bookingNumber": "10210",
        "bookingDate": "7/12/2024 7:30:00 PM",
        "age": "32",
        "gender": "F",
        "race": "W",
        "height": "5 ft 00in(s)",
        "weight": "135 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "CENTRAL BRIDGE, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10210.jpg"
    },
    {
        "name": "BRANDON CHARLES MACLAURY",
        "bookingNumber": "10231",
        "bookingDate": "7/11/2024 11:52:00 PM",
        "age": "38",
        "gender": "M",
        "race": "W",
        "height": "5 ft 05in(s)",
        "weight": "160 lbs",
        "hairColor": "BLK",
        "eyeColor": "HAZ",
        "city": "MCDONOUGH, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "/Images/Default/Blank.jpg"
    },
    {
        "name": "ALEJANDRO OROZCO",
        "bookingNumber": "10230",
        "bookingDate": "7/11/2024 11:06:00 PM",
        "age": "42",
        "gender": "M",
        "race": "NOMAP",
        "height": "5 ft 11in(s)",
        "weight": "180 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "FRANKLIN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10230.jpg"
    },
    {
        "name": "TARA GOSS",
        "bookingNumber": "10228",
        "bookingDate": "7/10/2024 12:17:00 PM",
        "age": "51",
        "gender": "F",
        "race": "W",
        "height": "5 ft 03in(s)",
        "weight": "130 lbs",
        "hairColor": "SDY",
        "eyeColor": "GRN",
        "city": "MIDDLEBURG, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10228.jpg"
    },
    {
        "name": "PETER PUGLISI",
        "bookingNumber": "10191",
        "bookingDate": "7/9/2024 11:49:00 AM",
        "age": "40",
        "gender": "M",
        "race": "W",
        "height": "5 ft 06in(s)",
        "weight": "125 lbs",
        "hairColor": "BLK",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10191.jpg"
    },
    {
        "name": "JEFFERY C KAUFMAN",
        "bookingNumber": "10227",
        "bookingDate": "7/9/2024 12:17:00 AM",
        "age": "54",
        "gender": "M",
        "race": "W",
        "height": "5 ft 04in(s)",
        "weight": "145 lbs",
        "hairColor": "GRY",
        "eyeColor": "BRO",
        "city": "NYDELAWARESO",
        "arrestingAgency": "none",
        "image": "/Images/Default/Blank.jpg"
    },
    {
        "name": "KAYLA M COONRADT",
        "bookingNumber": "10226",
        "bookingDate": "7/6/2024 9:26:00 PM",
        "age": "32",
        "gender": "F",
        "race": "W",
        "height": "5 ft 03in(s)",
        "weight": "180 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10226.jpg"
    },
    {
        "name": "TYLER LONG",
        "bookingNumber": "10223",
        "bookingDate": "7/3/2024 4:09:00 PM",
        "age": "27",
        "gender": "M",
        "race": "W",
        "height": "6 ft 02in(s)",
        "weight": "240 lbs",
        "hairColor": "BLN",
        "eyeColor": "BLU",
        "city": "SIDNEY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10223.jpg"
    },
    {
        "name": "MATHEW D JONES",
        "bookingNumber": "10222",
        "bookingDate": "7/3/2024 8:45:00 AM",
        "age": "27",
        "gender": "M",
        "race": "W",
        "height": "5 ft 06in(s)",
        "weight": "125 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "BAINBRIDGE, NY",
        "arrestingAgency": "none",
        "image": "https://recentlybooked.com/Images/2428/10222.jpg"
    },
    {
        "name": "GEORGE L MORALES",
        "bookingNumber": "7080",
        "bookingDate": "7/1/2024 5:56:00 PM",
        "age": "32",
        "gender": "M",
        "race": "NOMAP",
        "height": "6 ft 00in(s)",
        "weight": "280 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "SIDNEY, NY",
        "arrestingAgency": "none",
        "image": "https://recentlybooked.com/Images/2428/7080.jpg"
    },
    {
        "name": "KIM KRAEMER",
        "bookingNumber": "10182",
        "bookingDate": "7/1/2024 5:19:00 PM",
        "age": "52",
        "gender": "F",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "174 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "none",
        "image": "/Images/Default/Blankf.jpg"
    },
    {
        "name": "DANA A NASH",
        "bookingNumber": "10221",
        "bookingDate": "7/1/2024 10:55:00 AM",
        "age": "39",
        "gender": "M",
        "race": "W",
        "height": "5 ft 06in(s)",
        "weight": "140 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "SIDNEY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10221.jpg"
    },
    {
        "name": "ANDREW BESUGLOW",
        "bookingNumber": "10109",
        "bookingDate": "6/28/2024 9:22:00 PM",
        "age": "47",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "none",
        "image": "/Images/Default/Blank.jpg"
    },
    {
        "name": "PRESTON S WALKER",
        "bookingNumber": "7056",
        "bookingDate": "6/28/2024 6:34:00 PM",
        "age": "27",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "175 lbs",
        "hairColor": "BRO",
        "eyeColor": "GRN",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7056.jpg"
    },
    {
        "name": "ANDREW J BESUGLOW",
        "bookingNumber": "10110",
        "bookingDate": "6/28/2024 6:30:00 PM",
        "age": "47",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "SIDNEY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10110.jpg"
    },
    {
        "name": "THOMAS S DECKERT",
        "bookingNumber": "10107",
        "bookingDate": "6/28/2024 4:42:00 PM",
        "age": "45",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "165 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10107.jpg"
    },
    {
        "name": "CHRISTOPHER J HELLER",
        "bookingNumber": "7053",
        "bookingDate": "6/28/2024 4:30:00 PM",
        "age": "51",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "190 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7053.jpg"
    },
    {
        "name": "LEONARD T YACANO",
        "bookingNumber": "10183",
        "bookingDate": "6/28/2024 3:39:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "5 ft 06in(s)",
        "weight": "160 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "/Images/Default/Blank.jpg"
    },
    {
        "name": "WILLIAM J DEPUE",
        "bookingNumber": "10108",
        "bookingDate": "6/28/2024 2:43:00 PM",
        "age": "59",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "165 lbs",
        "hairColor": "BLD",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10108.jpg"
    },
    {
        "name": "PAUL J MCELROY",
        "bookingNumber": "7052",
        "bookingDate": "6/28/2024 1:59:00 PM",
        "age": "59",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "145 lbs",
        "hairColor": "GRY",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7052.jpg"
    },
    {
        "name": "THOMAS G SPERLING",
        "bookingNumber": "7055",
        "bookingDate": "6/28/2024 12:33:00 PM",
        "age": "63",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "190 lbs",
        "hairColor": "GRY",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7055.jpg"
    },
    {
        "name": "JAMES M GILBERT",
        "bookingNumber": "7051",
        "bookingDate": "6/28/2024 11:14:00 AM",
        "age": "46",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "175 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7051.jpg"
    },
    {
        "name": "ROBERT L MEREDITH",
        "bookingNumber": "7054",
        "bookingDate": "6/28/2024 10:57:00 AM",
        "age": "60",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "165 lbs",
        "hairColor": "SDY",
        "eyeColor": "GRN",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/7054.jpg"
    },
    {
        "name": "ALEXANDER A WALKER",
        "bookingNumber": "10106",
        "bookingDate": "6/27/2024 8:31:00 PM",
        "age": "24",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "160 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10106.jpg"
    },
    {
        "name": "ANDREW B BESUGLOW",
        "bookingNumber": "10057",
        "bookingDate": "6/27/2024 7:43:00 PM",
        "age": "47",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "SIDNEY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10057.jpg"
    },
    {
        "name": "JEREMY L ROE",
        "bookingNumber": "10053",
        "bookingDate": "6/27/2024 4:51:00 PM",
        "age": "35",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "140 lbs",
        "hairColor": "BLD",
        "eyeColor": "BLU",
        "city": "SCHENECTADY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10053.jpg"
    },
    {
        "name": "TRISTAN P BESUGLOW",
        "bookingNumber": "10054",
        "bookingDate": "6/27/2024 4:50:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "SIDNEY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10054.jpg"
    },
    {
        "name": "DANIEL T MCDONALD",
        "bookingNumber": "10056",
        "bookingDate": "6/27/2024 4:49:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "GRN",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10056.jpg"
    },
    {
        "name": "NICHOLAS GOLDOVSKY",
        "bookingNumber": "10055",
        "bookingDate": "6/27/2024 4:48:00 PM",
        "age": "38",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "SCHENECTADY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10055.jpg"
    },
    {
        "name": "DEEJAY J WILLS",
        "bookingNumber": "10050",
        "bookingDate": "6/27/2024 4:46:00 PM",
        "age": "32",
        "gender": "M",
        "race": "B",
        "height": "6 ft 00in(s)",
        "weight": "240 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "BINGHAMTON, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10050.jpg"
    },
    {
        "name": "MICHAEL F MURPHY",
        "bookingNumber": "10051",
        "bookingDate": "6/27/2024 4:46:00 PM",
        "age": "45",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "160 lbs",
        "hairColor": "SDY",
        "eyeColor": "BLU",
        "city": "SCHENECTADY, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10051.jpg"
    },
    {
        "name": "JONATHAN L HENDERSON",
        "bookingNumber": "10052",
        "bookingDate": "6/27/2024 4:45:00 PM",
        "age": "39",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "175 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10052.jpg"
    },
    {
        "name": "STUART A REILLY",
        "bookingNumber": "10049",
        "bookingDate": "6/27/2024 4:44:00 PM",
        "age": "41",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "215 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10049.jpg"
    },
    {
        "name": "JOHN M PRUNIER",
        "bookingNumber": "10048",
        "bookingDate": "6/27/2024 4:43:00 PM",
        "age": "63",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "190 lbs",
        "hairColor": "GRY",
        "eyeColor": "BLU",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10048.jpg"
    },
    {
        "name": "JAMES L DEWEY",
        "bookingNumber": "10047",
        "bookingDate": "6/27/2024 4:42:00 PM",
        "age": "43",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "210 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10047.jpg"
    },
    {
        "name": "ROBERT M JOHNSON",
        "bookingNumber": "10045",
        "bookingDate": "6/27/2024 4:40:00 PM",
        "age": "46",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "250 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10045.jpg"
    },
    {
        "name": "JEFFERY L HANCOCK",
        "bookingNumber": "10046",
        "bookingDate": "6/27/2024 4:40:00 PM",
        "age": "47",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "170 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10046.jpg"
    },
    {
        "name": "ADAM M FIELDS",
        "bookingNumber": "10044",
        "bookingDate": "6/27/2024 4:39:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "135 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10044.jpg"
    },
    {
        "name": "NICHOLAS J HALL",
        "bookingNumber": "10042",
        "bookingDate": "6/27/2024 4:38:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "190 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10042.jpg"
    },
    {
        "name": "COREY M PELTON",
        "bookingNumber": "10043",
        "bookingDate": "6/27/2024 4:38:00 PM",
        "age": "28",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "160 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10043.jpg"
    },
    {
        "name": "WILLIAM J ROBERTS",
        "bookingNumber": "10039",
        "bookingDate": "6/27/2024 4:36:00 PM",
        "age": "48",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "180 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10039.jpg"
    },
    {
        "name": "JUSTIN C HASKINS",
        "bookingNumber": "10041",
        "bookingDate": "6/27/2024 4:35:00 PM",
        "age": "32",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10041.jpg"
    },
    {
        "name": "JASON L MITCHELL",
        "bookingNumber": "10040",
        "bookingDate": "6/27/2024 4:34:00 PM",
        "age": "39",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "230 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10040.jpg"
    },
    {
        "name": "ROBERT R EVANS",
        "bookingNumber": "10038",
        "bookingDate": "6/27/2024 4:33:00 PM",
        "age": "36",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10038.jpg"
    },
    {
        "name": "NICHOLAS J RICHARD",
        "bookingNumber": "10037",
        "bookingDate": "6/27/2024 4:32:00 PM",
        "age": "30",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "165 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10037.jpg"
    },
    {
        "name": "MATTHEW L HUBBARD",
        "bookingNumber": "10036",
        "bookingDate": "6/27/2024 4:31:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "175 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10036.jpg"
    },
    {
        "name": "ERNESTO RAMIREZ",
        "bookingNumber": "10035",
        "bookingDate": "6/27/2024 4:30:00 PM",
        "age": "22",
        "gender": "M",
        "race": "H",
        "height": "5 ft 07in(s)",
        "weight": "145 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10035.jpg"
    },
    {
        "name": "EDWARD M LAMB",
        "bookingNumber": "10034",
        "bookingDate": "6/27/2024 4:29:00 PM",
        "age": "41",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "215 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10034.jpg"
    },
    {
        "name": "DAVID E HALL",
        "bookingNumber": "10033",
        "bookingDate": "6/27/2024 4:27:00 PM",
        "age": "27",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10033.jpg"
    },
    {
        "name": "DAVID A HUGHES",
        "bookingNumber": "10032",
        "bookingDate": "6/27/2024 4:26:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10032.jpg"
    },
    {
        "name": "ERICK J CARROLL",
        "bookingNumber": "10031",
        "bookingDate": "6/27/2024 4:25:00 PM",
        "age": "26",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "175 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10031.jpg"
    },
    {
        "name": "JAMES D ARTHUR",
        "bookingNumber": "10030",
        "bookingDate": "6/27/2024 4:24:00 PM",
        "age": "28",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "160 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "none",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10030.jpg"
    },
    {
        "name": "ROBERT T BROWN",
        "bookingNumber": "10029",
        "bookingDate": "6/27/2024 4:23:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "180 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10029.jpg"
    },
    {
        "name": "CHARLES A JACQUES",
        "bookingNumber": "10028",
        "bookingDate": "6/27/2024 4:22:00 PM",
        "age": "42",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10028.jpg"
    },
    {
        "name": "JORDAN M SHAMBO",
        "bookingNumber": "10027",
        "bookingDate": "6/27/2024 4:21:00 PM",
        "age": "30",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "180 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10027.jpg"
    },
    {
        "name": "PAUL A KERKER",
        "bookingNumber": "10026",
        "bookingDate": "6/27/2024 4:20:00 PM",
        "age": "43",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "220 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10026.jpg"
    },
    {
        "name": "JOHN M SCALZO",
        "bookingNumber": "10025",
        "bookingDate": "6/27/2024 4:19:00 PM",
        "age": "30",
        "gender": "M",
        "race": "W",
        "height": "6 ft 01in(s)",
        "weight": "175 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10025.jpg"
    },
    {
        "name": "EDWARD S UNGER",
        "bookingNumber": "10024",
        "bookingDate": "6/27/2024 4:17:00 PM",
        "age": "35",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "165 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10024.jpg"
    },
    {
        "name": "LUCAS A KELLY",
        "bookingNumber": "10023",
        "bookingDate": "6/27/2024 4:16:00 PM",
        "age": "43",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10023.jpg"
    },
    {
        "name": "DAVID R DRISCOLL",
        "bookingNumber": "10022",
        "bookingDate": "6/27/2024 4:15:00 PM",
        "age": "52",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10022.jpg"
    },
    {
        "name": "DANIEL R KITTREDGE",
        "bookingNumber": "10021",
        "bookingDate": "6/27/2024 4:14:00 PM",
        "age": "60",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "190 lbs",
        "hairColor": "BRO",
        "eyeColor": "GRN",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10021.jpg"
    },
    {
        "name": "JUSTIN L HART",
        "bookingNumber": "10020",
        "bookingDate": "6/27/2024 4:13:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10020.jpg"
    },
    {
        "name": "DANIEL J ANDREWS",
        "bookingNumber": "10019",
        "bookingDate": "6/27/2024 4:12:00 PM",
        "age": "37",
        "gender": "M",
        "race": "W",
        "height": "6 ft 01in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10019.jpg"
    },
    {
        "name": "JESSE D RIGNEY",
        "bookingNumber": "10018",
        "bookingDate": "6/27/2024 4:11:00 PM",
        "age": "32",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "180 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10018.jpg"
    },
    {
        "name": "CODY J HAINES",
        "bookingNumber": "10017",
        "bookingDate": "6/27/2024 4:10:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "165 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10017.jpg"
    },
    {
        "name": "DAVID A ROBERTS",
        "bookingNumber": "10016",
        "bookingDate": "6/27/2024 4:09:00 PM",
        "age": "35",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "160 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10016.jpg"
    },
    {
        "name": "DAVID L MINTZ",
        "bookingNumber": "10015",
        "bookingDate": "6/27/2024 4:08:00 PM",
        "age": "40",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "170 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10015.jpg"
    },
    {
        "name": "MICHAEL S DENAPOLI",
        "bookingNumber": "10014",
        "bookingDate": "6/27/2024 4:07:00 PM",
        "age": "33",
        "gender": "M",
        "race": "W",
        "height": "5 ft 07in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10014.jpg"
    },
    {
        "name": "JAMES A HURLEY",
        "bookingNumber": "10013",
        "bookingDate": "6/27/2024 4:06:00 PM",
        "age": "46",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "190 lbs",
        "hairColor": "BRO",
        "eyeColor": "GRN",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10013.jpg"
    },
    {
        "name": "KODY M FREEMAN",
        "bookingNumber": "10012",
        "bookingDate": "6/27/2024 4:05:00 PM",
        "age": "28",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "200 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10012.jpg"
    },
    {
        "name": "ADAM W FERNANDEZ",
        "bookingNumber": "10011",
        "bookingDate": "6/27/2024 4:04:00 PM",
        "age": "29",
        "gender": "M",
        "race": "W",
        "height": "5 ft 11in(s)",
        "weight": "190 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10011.jpg"
    },
    {
        "name": "JUSTIN P BURGESS",
        "bookingNumber": "10010",
        "bookingDate": "6/27/2024 4:03:00 PM",
        "age": "28",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "150 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10010.jpg"
    },
    {
        "name": "DARREL L LAMPERT",
        "bookingNumber": "10009",
        "bookingDate": "6/27/2024 4:02:00 PM",
        "age": "35",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "140 lbs",
        "hairColor": "BRO",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10009.jpg"
    },
    {
        "name": "JESSE J GRANT",
        "bookingNumber": "10008",
        "bookingDate": "6/27/2024 4:01:00 PM",
        "age": "24",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "145 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10008.jpg"
    },
    {
        "name": "JUSTIN M WALZ",
        "bookingNumber": "10007",
        "bookingDate": "6/27/2024 4:00:00 PM",
        "age": "31",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "200 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10007.jpg"
    },
    {
        "name": "DUSTIN J MCDANIEL",
        "bookingNumber": "10006",
        "bookingDate": "6/27/2024 3:59:00 PM",
        "age": "27",
        "gender": "M",
        "race": "W",
        "height": "5 ft 10in(s)",
        "weight": "170 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10006.jpg"
    },
    {
        "name": "DANIEL R SCHWARTZ",
        "bookingNumber": "10005",
        "bookingDate": "6/27/2024 3:57:00 PM",
        "age": "34",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "160 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10005.jpg"
    },
    {
        "name": "MATT S KENYON",
        "bookingNumber": "10004",
        "bookingDate": "6/27/2024 3:56:00 PM",
        "age": "37",
        "gender": "M",
        "race": "W",
        "height": "6 ft 00in(s)",
        "weight": "200 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10004.jpg"
    },
    {
        "name": "ANDREW J FRAZIER",
        "bookingNumber": "10003",
        "bookingDate": "6/27/2024 3:55:00 PM",
        "age": "33",
        "gender": "M",
        "race": "W",
        "height": "6 ft 01in(s)",
        "weight": "200 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10003.jpg"
    },
    {
        "name": "CODY W COOPER",
        "bookingNumber": "10002",
        "bookingDate": "6/27/2024 3:54:00 PM",
        "age": "32",
        "gender": "M",
        "race": "W",
        "height": "5 ft 09in(s)",
        "weight": "155 lbs",
        "hairColor": "BLK",
        "eyeColor": "BRO",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10002.jpg"
    },
    {
        "name": "CHARLES R WEIR",
        "bookingNumber": "10001",
        "bookingDate": "6/27/2024 3:53:00 PM",
        "age": "25",
        "gender": "M",
        "race": "W",
        "height": "5 ft 08in(s)",
        "weight": "160 lbs",
        "hairColor": "BRO",
        "eyeColor": "BLU",
        "city": "COOPERSTOWN, NY",
        "arrestingAgency": "NYDELAWARESO",
        "image": "https://recentlybooked.com/Images/2428/10001.jpg"
    }
]

const writtenData = convertToCSV(data);
fs.writeFileSync("Delaware.xlsx", writtenData)